package com.myspace.cc_limit_approval_app;
import java.util.*;
import java.lang.*;
import com.fasterxml.jackson.databind.*;
import org.json.*;
// import org.json.JSONTokener;
/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class LimitRaiseRequest implements java.io.Serializable {

	static final long serialVersionUID = 1;

	@org.kie.api.definition.type.Label("Customer ID")
	private java.lang.Long customerId;
	@org.kie.api.definition.type.Label("New limit value suggested by the customer")
	private java.math.BigDecimal requestedValue;
	@org.kie.api.definition.type.Label("Request status")
	private boolean status;
	@org.kie.api.definition.type.Label("Customer current score in the market")
	private java.lang.Long customerScore;
    @org.kie.api.definition.type.Label("Test message")
    Object message = new Object();
    // private java.lang.reflect.Array car[];
    // private java.lang.Object message;
    // ObjectMapper mapper = new ObjectMapper();
	public LimitRaiseRequest() {
	   // ObjectMapper mapper = new ObjectMapper();
	   // Object test = new Object();
	   // test = message;
	   // Object json = null;
    //     JSONArray jsonArray = null;
    //     try {
    //         json = new JSONTokener(message.toString()).nextValue();
    //     } catch (JSONException e) {
    //         e.printStackTrace();
    //     }
    //     if (json instanceof JSONArray) {
    //         jsonArray = (JSONArray) json;
    //     }
	   // System.out.println(jsonArray);
	   //message = "TEESTE";
	   //System.out.println(message);
	   //System.out.println(customerId);
	}

	public java.lang.Long getCustomerId() {
	   // System.out.println(customerId);
		return this.customerId;
	}

	public void setCustomerId(java.lang.Long customerId) {
		this.customerId = customerId;
	}

	public java.math.BigDecimal getRequestedValue() {
		return this.requestedValue;
	}

	public void setRequestedValue(java.math.BigDecimal requestedValue) {
		this.requestedValue = requestedValue;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public java.lang.Long getCustomerScore() {
		return this.customerScore;
	}

	public void setCustomerScore(java.lang.Long customerScore) {
		this.customerScore = customerScore;
	}
	
    public ArrayList<String> getmessage() {
        Object json = null;
        JSONArray jsonArray = null;
        String StringList = "";
        ArrayList<String> listdata = new ArrayList<String>();  
        try {
            json = new JSONTokener(message.toString()).nextValue();
        } catch (JSONException e) {
            e.printStackTrace();
        }
        if (json instanceof JSONArray) {
            jsonArray = (JSONArray) json;
        }
        // System.out.println(jsonArray);
        JSONObject jo = new JSONObject();
        try {
            jo.put("message",jsonArray);
            if (jsonArray != null) { 
              for (int i=0;i<jsonArray.length();i++){ 
                    listdata.add(jsonArray.getString(i));
              } 
            }
        // // System.out.println(jo.optString("message"));
        // // System.out.println(listdata.get(0).toString());
        // StringList = listdata.get(0);
        // // System.out.println(StringList);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        // System.out.println("original value: " + jo);
        // System.out.println(listdata);
        return listdata;
	}
	
	public void setmessage(java.lang.Object message) {
		this.message = message;
	}
	
	public LimitRaiseRequest(java.lang.Long customerId,
			java.math.BigDecimal requestedValue, boolean status,
			java.lang.Long customerScore ,java.lang.Object message) {
	     List<?> list = new ArrayList<>();
		this.customerId = customerId;
		this.requestedValue = requestedValue;
		this.status = status;
		this.customerScore = customerScore;
// 		message = message.getClass();
		this.message = message;
		
// 		System.out.println(message);
// 		return this.message;
	}
    
}
